### ISSUE TITLE
Python 3 Support or Need to be consistent

### ISSUE THREAD

**Issue by kkweon** [hunkim/PythonZeroToAll#6]
First, awesome project. I see it'd be valuable in the future for beginners.
But there are some points that I do not understand.
So I've decided to leave an early issue since it can be hard to fix later in the future.

## Summary
- I know it states that you can use `blah blah if you use python3`
- But considering this is for beginners, everything should be written in Python 3
     - currently, it seems it's based in Python 2
- or at least it should be consistent
    - sometimes it uses the `print statement` as in Python 2
    - sometimes it uses the `print(...) function` as in Python 3
    - check [this file](https://github.com/hunkim/PythonZeroToAll/blob/master/Lab01-3_Arithmetic-Operators.ipynb) for example

## Suggestion
- Drop Python 2 support or at least use Python3 as a base default language
- Why?
    - Python 2 is (almost) dead (it's legacy now at least)
        - it will only last until 2020
        - it won't get any update but only bug fixes. So, there are no new features
        - it's slow not as optimized as recent Python 3
    - Science community has moved to Python 3
        - Jupyter, for example, has already dropped Python 2....
        - ![big_science_lib](https://cloud.githubusercontent.com/assets/2981167/25643087/7fe3a49c-2f52-11e7-8790-00e0a7d1302e.png)
     - This is not just science community. The whole community has moved to Python3
        - Django dropped Python2 support
     - Remember `Zed Shaw` who was the author of `Learn Python Hard Way.`  [He was criticized by the community for recommending Python 2 over Python 3](https://news.ycombinator.com/item?id=13019819) a year ago and now he uses Python 3.

**Comment by hunkim** [comment]
I agree. @ejchoigo Could you look into this?

**Comment by ejchoigo** [comment]
@hunkim  Thank You :)

@kkweon 
Wow. 
Thank you for your comment.

This tutorial started with the problem of hackerrank.com, and since the site provided the contents of Python 2 and Python 3 at the same time, the tutorial naturally explained both versions simultaneously.
I will accept your advice and focus more on Python 3, and fix any inconsistencies in the previous section.

Again, thank you very much.

**Comment by kkweon** [comment]
@ejchoigo Cool :+1: I can't wait to see this project finished. Do you accept any contributions?

**Comment by hunkim** [comment]
We always welcome. :-)

**Comment by kkweon** [comment]
Cool :open_mouth: 
Any contribution guide will be helpful then.
Closing this issue now.
